### ISSUE TITLE
no_routes when trying to register

### ISSUE THREAD

**Issue by lodr** [mozillahispano/coseme#10]
Trying to register a number results in no_routes response from WA servers.

**Comment by willyaranda** [comment]
Related: https://github.com/mozillahispano/openwapp/issues/61

Pinging @aesedepece who told me that was going to work on this

**Comment by aesedepece** [comment]
Registration is broken again:
https://github.com/mgp25/WhatsAPI-Official/issues/341
https://github.com/tgalal/yowsup/issues/607

I assume that ```"WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302``` UA has been already banned.
