### ISSUE TITLE
Old version reports

### ISSUE THREAD

**Issue by Timmaks** [mozillahispano/coseme#18]
We receive a lot of user ratings on marketplace (openwapp) with the old version warning, does the config.js need a update?

**Comment by willyaranda** [comment]
It seems that https://github.com/WHAnonymous/Chat-API/commit/9fac63111bc120acd53ed6353e1f4712a9272f05 did some changes, adding a new token generation based on this always up-to-date config: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

We should use this tokens. I can work on this tomorrow evening.

**Comment by Timmaks** [comment]
i delayed the update for openwapp until this is fixed

**Comment by Timmaks** [comment]
Hi

Do you have time to fix this? I would really like to push a new 1.8.1 vrsion to the marketplace before i leave tomorrow for my pto

Greetings

Tim Maks




Verzonden vanaf Samsung-tablet.


-------- Oorspronkelijk bericht --------
Van: Guillermo López Leal <notifications@github.com> 
Datum: 15-07-2015  22:51  (GMT+01:00) 
Aan: mozillahispano/coseme <coseme@noreply.github.com> 
Cc: "T.M. van den Broek" <tim_maks@mozilla-nl.org> 
Onderwerp: Re: [coseme] Old version reports (#18) 

It seems that WHAnonymous/Chat-API@9fac631 did some changes, adding a new token generation based on this always up-to-date config: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

We should use this tokens. I can work on this tomorrow evening.
