### ISSUE TITLE
apply the changes in loqui

### ISSUE THREAD

**Issue by Timmaks** [mozillahispano/coseme#32]
Can this https://github.com/loqui/im/commit/876a16450e27b147e583c984840442918e2191bb be applied so openwapp can fix https://github.com/mozillahispano/openwapp/issues/171

**Comment by Timmaks** [comment]
I tested it in my build of openwapp and it works as expected

**Comment by willyaranda** [comment]
Yeah, sure. I will make the change! Thanks!

**Comment by willyaranda** [comment]
https://github.com/mozillahispano/coseme/commit/379dba477e7f6fbe25194b4e808a48e2bfc2e0bb
