### ISSUE TITLE
Avoid encrypted messages (for now)

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/coseme#6]
We need to avoid server to send encrypted messages.

Here they are suggesting to identify the client with a lower version:

https://github.com/mgp25/WhatsAPI-Official/issues/228

**Comment by willyaranda** [comment]
Loqui devs say that this should fix it! https://github.com/mozillahispano/coseme/commit/379dba477e7f6fbe25194b4e808a48e2bfc2e0bb
